name: Finn.io
url: https://finn.io
description: The personal website of Finn Herzfeld

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
